# NeoForge 模组配置文件
modLoader="javafml"
loaderVersion="[21,)"  # 对应MC 1.21.x
license="MIT"

# 你的模组信息
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Combat Perspective"
authors="YourName"
description="A.A.A"

# 加载 Mixin
mixins = ["combatperspective.mixins.json"]

[[dependencies.combatperspective]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.228,)"

[[dependencies.combatperspective]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.21.2)"   # 1.21.1 限定